### ISSUE TITLE
There is no option to set project directory

### ISSUE THREAD

**Issue by snowden2** [FutureWorkshops/bitrise-step-cocoapod-key#3]
Hello, Thanks for great library.
One thing I found missing is that we don't have the option to set the project directory.
Because of this, many guys who have project something like (aaa/bbb/bbb.xcworkspace) will get this error. 

> No Podfile found in the project directory.

Can you please update the library?
Thanks.

**Comment by igorcferreira** [comment]
@mobilestar1 Thanks for report the issue. I've made the fix, and created a PR to Bitrise's step library. Hopefully, it will be merged soon.

**Comment by snowden2** [comment]
@igorcferreira , Thanks for your quick response and I do appreciate it , I also hope It will be merged soon.

**Comment by igorcferreira** [comment]
@mobilestar1 I'll close this issue, since this is already implemented, just pending Bitrise approval.
