### ISSUE TITLE
"Keys array and Values array do not have the same size" when using Secret Environment Variables as values

### ISSUE THREAD

**Issue by blau2** [FutureWorkshops/bitrise-step-cocoapod-key#6]
We store our keys in Bitrise as Secret Environment Variables so that they don't get leaked in logs. It seems that they aren't properly parsed when the step is run. The following inputs result in the error `Keys array and Values array do not have the same size`.

Keys: `UXCamKeyStaging|UXCamKeyBeta|UXCamKeyProduction`
Values: `$UXCAM_KEY_STAGING|$UXCAM_KEY_BETA|$UXCAM_KEY_PRODUCTION`

Entering the values as plain text results in the step completing successfully, but that of course defeats the purpose of using `cocoapods-keys`.

**Comment by igorcferreira** [comment]
@blau2 We do have similar structure (value stored as Secret and applied into the step) in multiple projects, all working fine. Does you value contain the `|` character on it? Or any similar special character?

**Comment by blau2** [comment]
Hi @igorcferreira, yes we are separating each secret var with `|`. The variables have underscores in their name but I've tried without and still get the same result.

**Comment by igorcferreira** [comment]
I'm trying to create a reproducible scenario that I debug against and add a test case, to investigate and fix the issue.

**Comment by alielsokary** [comment]
I'm having the same issue. my key is a jwt. typing the value as plain text passes.

**Comment by igorcferreira** [comment]
In [version 2.0.0](https://github.com/FutureWorkshops/bitrise-step-cocoapod-key/tree/2.0.0) of this step, the keys & values arrays were removed. These inputs were presenting too many issues, and in general, mutating the keychain of the VM is not a great approach.

The best practice to use [cocoapods-key in a CI environment](https://github.com/orta/cocoapods-keys#continuous-integration) is to have the values as Bitrise's Secret.

For example, given that you have a configuration similar to this on your Podfile:

```
plugin 'cocoapods-keys', {
	:project => "App",
	:keys => [
		"APIClientSecret",
		"APIClientKey"
	]
}
```

To properly use cocoapods-key, `APIClientSecret` and `APIClientKey` should be added as secret ENV. This way, when "pod install" is executed, the value from these secrets will be used to generate the Key class with the obfuscated values.

If you need to populate the keys with values from other steps, you can use `envman add` prior to `pod install`, or `pod keys exec ... & pod keys generate ...` for that specific key after pod install.
